name: case_digital_wallet
description: CASE - Billetera Digital MVP
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.8
  go_router: ^14.2.7
  flutter_bloc: ^8.1.6
  
  # HTTP & API
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  json_annotation: ^4.9.0
  
  # Storage & Security
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3
  
  # Authentication & Biometrics
  local_auth: ^2.2.0
  crypto: ^3.0.3
  
  # Camera & QR
  camera: ^0.10.6
  mobile_scanner: ^5.1.1
  qr_flutter: ^4.1.0
  
  # Image handling
  image_picker: ^1.1.2
  
  # Push notifications
  firebase_core: ^2.31.1
  firebase_messaging: ^14.9.4
  
  # SMS & Phone
  sms_autofill: ^2.4.0
  
  # Utils
  intl: ^0.19.0
  equatable: ^2.0.5
  get_it: ^7.7.0
  
  # Permissions
  permission_handler: ^11.3.1
  
  # File handling
  path_provider: ^2.1.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Code generation
  build_runner: ^2.4.12
  retrofit_generator: ^8.1.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700